apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.indexCapability.indexingModelPVC.name }}
spec:
  {{- if .Values.indexCapability.indexingModelPVC.name }}
  storageClassName: {{ .Values.indexCapability.indexingModelPVC.storageClassName }}
  {{- end }}
  accessModes:
    - {{ .Values.indexCapability.indexingModelPVC.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.indexCapability.indexingModelPVC.storage | quote }}