apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.inferenceCapability.pvc.name }}
spec:
  {{- if .Values.inferenceCapability.pvc.name }}
  storageClassName: {{ .Values.inferenceCapability.pvc.storageClassName }}
  {{- end }}
  accessModes:
    {{- toYaml .Values.inferenceCapability.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.inferenceCapability.pvc.storage }}
